# https://docs.travis-ci.com/user/languages/java/
language: java

# Notifications https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - brokilone@yandex.ru
    on_success: always # default: change
    on_failure: always # default: always
